import { X, Mail, Check, FileText } from 'lucide-react';
import type { AuditLog } from '@/types';

interface WeeklySummaryModalProps {
  logs: AuditLog[];
  onClose: () => void;
  onConfirm: (logIds: string[]) => void;
}

export default function WeeklySummaryModal({ logs, onClose, onConfirm }: WeeklySummaryModalProps) {
  const now = new Date();
  const weekStart = new Date(now);
  weekStart.setDate(now.getDate() - 7);

  const formatDate = (d: Date) => d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const groupedByType: Record<string, AuditLog[]> = {};
  for (const log of logs) {
    if (!groupedByType[log.change_type]) groupedByType[log.change_type] = [];
    groupedByType[log.change_type].push(log);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm" onClick={onClose}>
      <div className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600">
              <Mail className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-slate-800">Weekly Summary Email Preview</h2>
              <p className="text-xs text-slate-400">This is what Make.com will send to management</p>
            </div>
          </div>
          <button onClick={onClose} className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="max-h-[55vh] overflow-y-auto px-6 py-5">
          <div className="rounded-xl border border-slate-200 bg-slate-50">
            <div className="border-b border-slate-200 bg-gradient-to-r from-indigo-600 to-slate-700 rounded-t-xl px-5 py-4">
              <h3 className="text-lg font-bold text-white">Weekly Asset Change Summary</h3>
              <p className="text-sm text-indigo-100">
                {formatDate(weekStart)} — {formatDate(now)}
              </p>
            </div>

            <div className="space-y-4 p-5">
              <p className="text-sm text-slate-600">
                The following <strong>{logs.length}</strong> asset change{logs.length !== 1 ? 's' : ''} were recorded this week
                and require management attention:
              </p>

              {Object.entries(groupedByType).map(([type, typeLogs]) => (
                <div key={type}>
                  <h4 className="mb-2 text-sm font-semibold text-slate-700">
                    {type} Changes ({typeLogs.length})
                  </h4>
                  <div className="space-y-1.5">
                    {typeLogs.map((log) => (
                      <div key={log.id} className="flex items-start gap-2 rounded-lg bg-white px-3 py-2 text-xs">
                        <FileText className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" />
                        <div className="flex-1">
                          <span className="font-medium text-slate-700">{log.asset_name}</span>
                          <span className="text-slate-400"> ({log.asset_tag})</span>
                          <span className="text-slate-500"> — changed from </span>
                          <span className="font-medium text-slate-600">{log.previous_value || '—'}</span>
                          <span className="text-slate-500"> to </span>
                          <span className="font-medium text-slate-600">{log.new_value || '—'}</span>
                        </div>
                        <span className="shrink-0 text-slate-400">{log.updated_by}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}

              <div className="border-t border-slate-200 pt-3 text-xs text-slate-400">
                <p>This report was generated by AssetHub and is ready for distribution via Make.com automation.</p>
                <p className="mt-1">Upon confirmation, all listed entries will be marked as reported to management.</p>
              </div>
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between border-t border-slate-200 px-6 py-4">
          <p className="text-xs text-slate-400">
            {logs.length} log entries will be marked as reported
          </p>
          <div className="flex gap-3">
            <button
              onClick={onClose}
              className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50"
            >
              Cancel
            </button>
            <button
              onClick={() => onConfirm(logs.map((l) => l.id))}
              className="flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-emerald-700"
            >
              <Check className="h-4 w-4" /> Confirm & Mark Reported
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
